"""empty message

Revision ID: 43b255b401ea
Revises: a5bf93f75b4f
Create Date: 2019-04-15 15:54:56.411176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b255b401ea'
down_revision = 'a5bf93f75b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('posts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'posts')
    # ### end Alembic commands ###
