"""new

Revision ID: b1a25cd6c7de
Revises: a339f5a045a7
Create Date: 2019-03-24 10:25:55.027399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a25cd6c7de'
down_revision = 'a339f5a045a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_created'), 'comment', ['created'], unique=False)
    op.add_column('post', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'post_id')
    op.drop_index(op.f('ix_comment_created'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
