"""empty message

Revision ID: f4b6c34f05e8
Revises: 43b255b401ea
Create Date: 2019-04-15 15:57:54.835994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b6c34f05e8'
down_revision = '43b255b401ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'post', ['post_id'], ['id'])
    op.drop_column('user', 'posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('posts', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'post_id')
    # ### end Alembic commands ###
